name: Publish on PyPI

on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine mypy

    - name: Generate stubs
      run: |
        stubgen helixswarm -o .

    - name: Build and publish (helix-swarm)
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

    - name: Build and publish alias (helixswarm)
      run: |
        sed -i 's/helix-swarm/helixswarm/g' setup.cfg
        python setup.py sdist bdist_wheel
        twine upload dist/*
